# Generated by Django 4.2.30 on 2026-06-10 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import universities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=200)),
                ('university_type', models.CharField(choices=[('reach', 'Reach'), ('match', 'Match'), ('safety', 'Safety')], default='match', max_length=10)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('submitted', 'Submitted'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='preparing', max_length=15)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat_reading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sat_math', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ielts_overall', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ielts_listening', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ielts_reading', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ielts_writing', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ielts_speaking', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('toefl_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toefl_reading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toefl_listening', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toefl_speaking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toefl_writing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.university')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('sop', 'Statement of Purpose'), ('lor', 'Letter of Recommendation'), ('transcript', 'Transcript'), ('cv', 'CV / Resume'), ('essay', 'Essay'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=universities.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
