# Generated by Django 4.2.30 on 2026-06-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_document_id_alter_scholarship_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('sop', 'Statement of Purpose'), ('lor', 'Letter of Recommendation'), ('transcript', 'Official Transcripts'), ('cv', 'CV / Resume'), ('essay', 'Supplemental Essay'), ('test_score', 'Test Score Submission'), ('financials', 'Financial Documents'), ('visa', 'Visa / Immigration Docs'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='universities.university')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
