# Generated by Django 4.2.30 on 2026-06-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_applicationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='avg_sat',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average SAT of admitted students', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_ielts',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum IELTS overall band', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='min_toefl',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum TOEFL iBT total', null=True),
        ),
    ]
