# Generated by Django 4.2.30 on 2026-06-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_avg_sat_university_min_ielts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='avg_sat',
        ),
        migrations.RemoveField(
            model_name='university',
            name='min_ielts',
        ),
        migrations.RemoveField(
            model_name='university',
            name='min_toefl',
        ),
    ]
