# Generated by Django 4.2.30 on 2026-06-12 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_remove_university_avg_sat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='ielts_listening',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='ielts_overall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='ielts_reading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='ielts_speaking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='ielts_writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.0)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='sat_math',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='sat_reading',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefl_listening',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefl_reading',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefl_speaking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefl_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='testscore',
            name='toefl_writing',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
